# JVM 参数：项目级会覆盖 GRADLE_USER_HOME 的全局配置，因此代理必须在这里也写一份
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=10808 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=10808

# 依赖下载代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
